# Generated by Django 5.1.5 on 2025-02-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_menu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Price',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
