# Generated by Django 5.1.3 on 2025-02-28 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_drink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='No_of_guests',
            new_name='reservation_slots',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='BookingDate',
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation_date',
            field=models.DateField(default=datetime.date(2025, 2, 28)),
            preserve_default=False,
        ),
    ]
