# Generated by Django 5.1.3 on 2025-03-01 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_rename_name_booking_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='first_name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='reservation_slots',
            new_name='No_of_guests',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='reservation_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='BookingDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 1, 9, 56, 40, 16569, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
